# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.3

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/simongrosse/Concretisation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/simongrosse/Concretisation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/simongrosse/Concretisation/CMakeFiles /Users/simongrosse/Concretisation//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/simongrosse/Concretisation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Pixies

# Build rule for target.
Pixies: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Pixies
.PHONY : Pixies

# fast build rule for target.
Pixies/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/build
.PHONY : Pixies/fast

sources/Carte.o: sources/Carte.cpp.o
.PHONY : sources/Carte.o

# target to build an object file
sources/Carte.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Carte.cpp.o
.PHONY : sources/Carte.cpp.o

sources/Carte.i: sources/Carte.cpp.i
.PHONY : sources/Carte.i

# target to preprocess a source file
sources/Carte.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Carte.cpp.i
.PHONY : sources/Carte.cpp.i

sources/Carte.s: sources/Carte.cpp.s
.PHONY : sources/Carte.s

# target to generate assembly for a file
sources/Carte.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Carte.cpp.s
.PHONY : sources/Carte.cpp.s

sources/Defausse.o: sources/Defausse.cpp.o
.PHONY : sources/Defausse.o

# target to build an object file
sources/Defausse.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Defausse.cpp.o
.PHONY : sources/Defausse.cpp.o

sources/Defausse.i: sources/Defausse.cpp.i
.PHONY : sources/Defausse.i

# target to preprocess a source file
sources/Defausse.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Defausse.cpp.i
.PHONY : sources/Defausse.cpp.i

sources/Defausse.s: sources/Defausse.cpp.s
.PHONY : sources/Defausse.s

# target to generate assembly for a file
sources/Defausse.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Defausse.cpp.s
.PHONY : sources/Defausse.cpp.s

sources/Grille.o: sources/Grille.cpp.o
.PHONY : sources/Grille.o

# target to build an object file
sources/Grille.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Grille.cpp.o
.PHONY : sources/Grille.cpp.o

sources/Grille.i: sources/Grille.cpp.i
.PHONY : sources/Grille.i

# target to preprocess a source file
sources/Grille.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Grille.cpp.i
.PHONY : sources/Grille.cpp.i

sources/Grille.s: sources/Grille.cpp.s
.PHONY : sources/Grille.s

# target to generate assembly for a file
sources/Grille.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Grille.cpp.s
.PHONY : sources/Grille.cpp.s

sources/Joueur.o: sources/Joueur.cpp.o
.PHONY : sources/Joueur.o

# target to build an object file
sources/Joueur.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Joueur.cpp.o
.PHONY : sources/Joueur.cpp.o

sources/Joueur.i: sources/Joueur.cpp.i
.PHONY : sources/Joueur.i

# target to preprocess a source file
sources/Joueur.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Joueur.cpp.i
.PHONY : sources/Joueur.cpp.i

sources/Joueur.s: sources/Joueur.cpp.s
.PHONY : sources/Joueur.s

# target to generate assembly for a file
sources/Joueur.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Joueur.cpp.s
.PHONY : sources/Joueur.cpp.s

sources/Pioche.o: sources/Pioche.cpp.o
.PHONY : sources/Pioche.o

# target to build an object file
sources/Pioche.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Pioche.cpp.o
.PHONY : sources/Pioche.cpp.o

sources/Pioche.i: sources/Pioche.cpp.i
.PHONY : sources/Pioche.i

# target to preprocess a source file
sources/Pioche.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Pioche.cpp.i
.PHONY : sources/Pioche.cpp.i

sources/Pioche.s: sources/Pioche.cpp.s
.PHONY : sources/Pioche.s

# target to generate assembly for a file
sources/Pioche.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/Pioche.cpp.s
.PHONY : sources/Pioche.cpp.s

sources/main.o: sources/main.cpp.o
.PHONY : sources/main.o

# target to build an object file
sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/main.cpp.o
.PHONY : sources/main.cpp.o

sources/main.i: sources/main.cpp.i
.PHONY : sources/main.i

# target to preprocess a source file
sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/main.cpp.i
.PHONY : sources/main.cpp.i

sources/main.s: sources/main.cpp.s
.PHONY : sources/main.s

# target to generate assembly for a file
sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Pixies.dir/build.make CMakeFiles/Pixies.dir/sources/main.cpp.s
.PHONY : sources/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Pixies"
	@echo "... sources/Carte.o"
	@echo "... sources/Carte.i"
	@echo "... sources/Carte.s"
	@echo "... sources/Defausse.o"
	@echo "... sources/Defausse.i"
	@echo "... sources/Defausse.s"
	@echo "... sources/Grille.o"
	@echo "... sources/Grille.i"
	@echo "... sources/Grille.s"
	@echo "... sources/Joueur.o"
	@echo "... sources/Joueur.i"
	@echo "... sources/Joueur.s"
	@echo "... sources/Pioche.o"
	@echo "... sources/Pioche.i"
	@echo "... sources/Pioche.s"
	@echo "... sources/main.o"
	@echo "... sources/main.i"
	@echo "... sources/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

